--------------------------------------------------------
--  파일이 생성됨 - 일요일-11월-27-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence BA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HYEONJU"."BA_SEQ"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 155 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MEMBER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HYEONJU"."MEMBER_SEQ"  MINVALUE 1000000 MAXVALUE 9999999 INCREMENT BY 1 START WITH 1000001 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence NEWS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HYEONJU"."NEWS_SEQ"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence NOTICE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HYEONJU"."NOTICE_SEQ"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence POST_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HYEONJU"."POST_SEQ"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 42 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence QNA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HYEONJU"."QNA_SEQ"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ADMIN
--------------------------------------------------------

  CREATE TABLE "HYEONJU"."ADMIN" 
   (	"ID" VARCHAR2(20 BYTE), 
	"name" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(40 BYTE), 
	"dept" VARCHAR2(20 BYTE), 
	"rank" VARCHAR2(20 BYTE), 
	"email" VARCHAR2(20 BYTE), 
	"birth" DATE, 
	"tel" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BANK
--------------------------------------------------------

  CREATE TABLE "HYEONJU"."BANK" 
   (	"NAME" VARCHAR2(20 BYTE), 
	"rate" NUMBER DEFAULT 1.0, 
	"CODE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BANK_ACCOUNT
--------------------------------------------------------

  CREATE TABLE "HYEONJU"."BANK_ACCOUNT" 
   (	"BANKNUMBER" VARCHAR2(20 BYTE), 
	"BANK" VARCHAR2(20 BYTE), 
	"ID" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"BALANCE" NUMBER, 
	"RATE" NUMBER, 
	"STATUS" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"CREATIONDATE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DEAL
--------------------------------------------------------

  CREATE TABLE "HYEONJU"."DEAL" 
   (	"no" NUMBER, 
	"type" VARCHAR2(20 BYTE), 
	"date" DATE, 
	"hostBank" VARCHAR2(20 BYTE), 
	"hostBankAccount" VARCHAR2(20 BYTE), 
	"targetBank" VARCHAR2(20 BYTE), 
	"targetBankAccount" VARCHAR2(20 BYTE), 
	"balance" NUMBER, 
	"targetShow" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "HYEONJU"."MEMBER" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(40 BYTE), 
	"BIRTH" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(40 BYTE), 
	"TEL" VARCHAR2(20 BYTE), 
	"GENDER" VARCHAR2(20 BYTE), 
	"RANK" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table POST
--------------------------------------------------------

  CREATE TABLE "HYEONJU"."POST" 
   (	"NO" NUMBER, 
	"CATEGORY" VARCHAR2(50 BYTE), 
	"TITLE" VARCHAR2(50 BYTE), 
	"WRITER" VARCHAR2(20 BYTE), 
	"CONTENTS" VARCHAR2(2048 BYTE), 
	"DATEOFISSUE" TIMESTAMP (6), 
	"AVAILABLE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into HYEONJU.ADMIN
SET DEFINE OFF;
Insert into HYEONJU.ADMIN (ID,"name",PASSWORD,"dept","rank","email","birth","tel") values ('admin1234','조현주','qwe123','dev','emp','admin@test.com',to_date('00/05/30','RR/MM/DD'),'01012341234');
Insert into HYEONJU.ADMIN (ID,"name",PASSWORD,"dept","rank","email","birth","tel") values ('admin123','조현주','qwe123','dev','emp','admin@test.com',to_date('00/05/30','RR/MM/DD'),'01012341234');
Insert into HYEONJU.ADMIN (ID,"name",PASSWORD,"dept","rank","email","birth","tel") values ('admin','조현주','qwe123','marketing','emp','qwe123',to_date('00/05/30','RR/MM/DD'),'01012341234');
Insert into HYEONJU.ADMIN (ID,"name",PASSWORD,"dept","rank","email","birth","tel") values ('admin12345','조현주','qwe123','finance','emp','test02@admin.org',to_date('00/05/30','RR/MM/DD'),'01012345678');
REM INSERTING into HYEONJU.BANK
SET DEFINE OFF;
Insert into HYEONJU.BANK (NAME,"rate",CODE) values ('개혁은행',1.28,'gh1234');
REM INSERTING into HYEONJU.BANK_ACCOUNT
SET DEFINE OFF;
Insert into HYEONJU.BANK_ACCOUNT (BANKNUMBER,BANK,ID,PASSWORD,BALANCE,RATE,STATUS,NAME,CREATIONDATE) values ('12340000041','개혁은행',null,'1234',0,1,'대기','개혁예적금','22/11/21');
Insert into HYEONJU.BANK_ACCOUNT (BANKNUMBER,BANK,ID,PASSWORD,BALANCE,RATE,STATUS,NAME,CREATIONDATE) values ('12340000043','개혁은행','test1234','1234',300000000,1,'대기','개혁예적금','22/11/21');
Insert into HYEONJU.BANK_ACCOUNT (BANKNUMBER,BANK,ID,PASSWORD,BALANCE,RATE,STATUS,NAME,CREATIONDATE) values ('12340000042','개혁은행','test1234','1234',20000,1,'대기','개혁예적금','22/11/21');
Insert into HYEONJU.BANK_ACCOUNT (BANKNUMBER,BANK,ID,PASSWORD,BALANCE,RATE,STATUS,NAME,CREATIONDATE) values ('12340000044','개혁은행','test1234','1234',0,1,'대기','개혁예적금','22/11/21');
Insert into HYEONJU.BANK_ACCOUNT (BANKNUMBER,BANK,ID,PASSWORD,BALANCE,RATE,STATUS,NAME,CREATIONDATE) values ('12340000045','개혁은행','test1234','1234',0,1,'대기','개혁예적금','22/11/21');
Insert into HYEONJU.BANK_ACCOUNT (BANKNUMBER,BANK,ID,PASSWORD,BALANCE,RATE,STATUS,NAME,CREATIONDATE) values ('12340000046','개혁은행','juuyeoon','1027',769898879,1,'대기','개혁예적금','22/11/21');
REM INSERTING into HYEONJU.DEAL
SET DEFINE OFF;
REM INSERTING into HYEONJU.MEMBER
SET DEFINE OFF;
Insert into HYEONJU.MEMBER (ID,NAME,PASSWORD,BIRTH,EMAIL,TEL,GENDER,RANK) values ('test1234','조현주','qwe123','000530','hyeonju.dlf@gmai','male','01012341234',1);
Insert into HYEONJU.MEMBER (ID,NAME,PASSWORD,BIRTH,EMAIL,TEL,GENDER,RANK) values ('test123445','조현주','qwe123','000530','hyeonju.dlf@gmai','male','01012341234',1);
Insert into HYEONJU.MEMBER (ID,NAME,PASSWORD,BIRTH,EMAIL,TEL,GENDER,RANK) values ('juuyeoon','현주바보','guswnqkqh','981016','hyeonju_babo@gmail.com','01020211027','female',1);
REM INSERTING into HYEONJU.POST
SET DEFINE OFF;
Insert into HYEONJU.POST (NO,CATEGORY,TITLE,WRITER,CONTENTS,DATEOFISSUE,AVAILABLE) values (2,'news','12',null,'1',to_timestamp('22/11/27 13:36:25.000000000','RR/MM/DD HH24:MI:SSXFF'),'1');
Insert into HYEONJU.POST (NO,CATEGORY,TITLE,WRITER,CONTENTS,DATEOFISSUE,AVAILABLE) values (3,'news','1212',null,'1212',to_timestamp('22/11/27 13:37:56.000000000','RR/MM/DD HH24:MI:SSXFF'),'1');
Insert into HYEONJU.POST (NO,CATEGORY,TITLE,WRITER,CONTENTS,DATEOFISSUE,AVAILABLE) values (1,'notice','1',null,'1',to_timestamp('22/11/27 13:35:15.000000000','RR/MM/DD HH24:MI:SSXFF'),'1');
--------------------------------------------------------
--  DDL for Index ADMIN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HYEONJU"."ADMIN_PK" ON "HYEONJU"."ADMIN" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index POST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HYEONJU"."POST_PK" ON "HYEONJU"."POST" ("NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MEMBER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HYEONJU"."MEMBER_PK" ON "HYEONJU"."MEMBER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index POST_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "HYEONJU"."POST_PK1" ON "HYEONJU"."POST" ("NO", "CATEGORY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BANK_ACCOUNT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HYEONJU"."BANK_ACCOUNT_PK" ON "HYEONJU"."BANK_ACCOUNT" ("BANKNUMBER", "BANK") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HYEONJU"."TABLE1_PK" ON "HYEONJU"."DEAL" ("no") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BANK_NAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "HYEONJU"."BANK_NAME" ON "HYEONJU"."BANK" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table DEAL
--------------------------------------------------------

  ALTER TABLE "HYEONJU"."DEAL" MODIFY ("no" NOT NULL ENABLE);
  ALTER TABLE "HYEONJU"."DEAL" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("no")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table POST
--------------------------------------------------------

  ALTER TABLE "HYEONJU"."POST" ADD CONSTRAINT "POST_PK" PRIMARY KEY ("NO", "CATEGORY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HYEONJU"."POST" MODIFY ("NO" NOT NULL ENABLE);
  ALTER TABLE "HYEONJU"."POST" MODIFY ("CATEGORY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BANK
--------------------------------------------------------

  ALTER TABLE "HYEONJU"."BANK" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "HYEONJU"."BANK" MODIFY ("rate" NOT NULL ENABLE);
  ALTER TABLE "HYEONJU"."BANK" ADD CONSTRAINT "BANK_NAME" PRIMARY KEY ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HYEONJU"."BANK" MODIFY ("CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "HYEONJU"."MEMBER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "HYEONJU"."MEMBER" ADD CONSTRAINT "MEMBER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ADMIN
--------------------------------------------------------

  ALTER TABLE "HYEONJU"."ADMIN" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "HYEONJU"."ADMIN" ADD CONSTRAINT "ADMIN_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BANK_ACCOUNT
--------------------------------------------------------

  ALTER TABLE "HYEONJU"."BANK_ACCOUNT" MODIFY ("BANKNUMBER" NOT NULL ENABLE);
  ALTER TABLE "HYEONJU"."BANK_ACCOUNT" MODIFY ("BANK" NOT NULL ENABLE);
  ALTER TABLE "HYEONJU"."BANK_ACCOUNT" ADD CONSTRAINT "BANK_ACCOUNT_PK" PRIMARY KEY ("BANKNUMBER", "BANK")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BANK_ACCOUNT
--------------------------------------------------------

  ALTER TABLE "HYEONJU"."BANK_ACCOUNT" ADD CONSTRAINT "BANK" FOREIGN KEY ("BANK")
	  REFERENCES "HYEONJU"."BANK" ("NAME") ENABLE;
  ALTER TABLE "HYEONJU"."BANK_ACCOUNT" ADD CONSTRAINT "USERID" FOREIGN KEY ("ID")
	  REFERENCES "HYEONJU"."MEMBER" ("ID") ENABLE;
