--------------------------------------------------------
--  파일이 생성됨 - 토요일-11월-19-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence BA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HYEONJU"."BA_SEQ"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 34 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MEMBER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HYEONJU"."MEMBER_SEQ"  MINVALUE 1000000 MAXVALUE 9999999 INCREMENT BY 1 START WITH 1000001 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ADMIN
--------------------------------------------------------

  CREATE TABLE "HYEONJU"."ADMIN" 
   (	"ID" VARCHAR2(20 BYTE), 
	"name" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(40 BYTE), 
	"dept" VARCHAR2(20 BYTE), 
	"rank" VARCHAR2(20 BYTE), 
	"email" VARCHAR2(20 BYTE), 
	"birth" DATE, 
	"tel" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BANK
--------------------------------------------------------

  CREATE TABLE "HYEONJU"."BANK" 
   (	"NAME" VARCHAR2(20 BYTE), 
	"rate" NUMBER DEFAULT 1.0, 
	"CODE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BANK_ACCOUNT
--------------------------------------------------------

  CREATE TABLE "HYEONJU"."BANK_ACCOUNT" 
   (	"BANKNUMBER" VARCHAR2(20 BYTE), 
	"BANK" VARCHAR2(20 BYTE), 
	"ID" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"BALANCE" NUMBER, 
	"RATE" NUMBER, 
	"STATUS" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"CREATIONDATE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DEAL
--------------------------------------------------------

  CREATE TABLE "HYEONJU"."DEAL" 
   (	"no" NUMBER, 
	"type" VARCHAR2(20 BYTE), 
	"date" DATE, 
	"hostBank" VARCHAR2(20 BYTE), 
	"hostBankAccount" VARCHAR2(20 BYTE), 
	"targetBank" VARCHAR2(20 BYTE), 
	"targetBankAccount" VARCHAR2(20 BYTE), 
	"balance" NUMBER, 
	"targetShow" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "HYEONJU"."MEMBER" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(40 BYTE), 
	"BIRTH" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"TEL" VARCHAR2(20 BYTE), 
	"GENDER" VARCHAR2(20 BYTE), 
	"RANK" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table POST
--------------------------------------------------------

  CREATE TABLE "HYEONJU"."POST" 
   (	"no" NUMBER, 
	"title" VARCHAR2(50 BYTE), 
	"writer" VARCHAR2(20 BYTE), 
	"contents" VARCHAR2(2048 BYTE), 
	"date" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into HYEONJU.ADMIN
SET DEFINE OFF;
Insert into HYEONJU.ADMIN (ID,"name",PASSWORD,"dept","rank","email","birth","tel") values ('admin1234','조현주','qwe123','dev','emp','admin@test.com',to_date('00/05/30','RR/MM/DD'),'01012341234');
Insert into HYEONJU.ADMIN (ID,"name",PASSWORD,"dept","rank","email","birth","tel") values ('admin123','조현주','qwe123','dev','emp','admin@test.com',to_date('00/05/30','RR/MM/DD'),'01012341234');
Insert into HYEONJU.ADMIN (ID,"name",PASSWORD,"dept","rank","email","birth","tel") values ('admin','조현주','qwe123','marketing','emp','qwe123',to_date('00/05/30','RR/MM/DD'),'01012341234');
Insert into HYEONJU.ADMIN (ID,"name",PASSWORD,"dept","rank","email","birth","tel") values ('admin12345','조현주','qwe123','finance','emp','test02@admin.org',to_date('00/05/30','RR/MM/DD'),'01012345678');
REM INSERTING into HYEONJU.BANK
SET DEFINE OFF;
Insert into HYEONJU.BANK (NAME,"rate",CODE) values ('개혁은행',1.28,'gh1234');
REM INSERTING into HYEONJU.BANK_ACCOUNT
SET DEFINE OFF;
Insert into HYEONJU.BANK_ACCOUNT (BANKNUMBER,BANK,ID,PASSWORD,BALANCE,RATE,STATUS,NAME,CREATIONDATE) values ('12340000004','개혁은행',null,'1234',0,1,'개혁예적금','대기','22/11/19');
Insert into HYEONJU.BANK_ACCOUNT (BANKNUMBER,BANK,ID,PASSWORD,BALANCE,RATE,STATUS,NAME,CREATIONDATE) values ('12340000012','개혁은행',null,'1234',0,1,'개혁예적금','대기','22/11/19');
Insert into HYEONJU.BANK_ACCOUNT (BANKNUMBER,BANK,ID,PASSWORD,BALANCE,RATE,STATUS,NAME,CREATIONDATE) values ('12340000014','개혁은행',null,null,0,1,'개혁예적금','대기','22/11/19');
Insert into HYEONJU.BANK_ACCOUNT (BANKNUMBER,BANK,ID,PASSWORD,BALANCE,RATE,STATUS,NAME,CREATIONDATE) values ('12340000003','개혁은행','test1234','1234',0,1,'개혁예적금','대기','22/11/19');
Insert into HYEONJU.BANK_ACCOUNT (BANKNUMBER,BANK,ID,PASSWORD,BALANCE,RATE,STATUS,NAME,CREATIONDATE) values ('12340000005','개혁은행',null,null,0,1,'개혁예적금','대기','22/11/19');
Insert into HYEONJU.BANK_ACCOUNT (BANKNUMBER,BANK,ID,PASSWORD,BALANCE,RATE,STATUS,NAME,CREATIONDATE) values ('12340000006','개혁은행',null,null,0,1,'개혁예적금','대기','22/11/19');
Insert into HYEONJU.BANK_ACCOUNT (BANKNUMBER,BANK,ID,PASSWORD,BALANCE,RATE,STATUS,NAME,CREATIONDATE) values ('12340000007','개혁은행','test1234','1234',0,1,'개혁예적금','대기','22/11/19');
Insert into HYEONJU.BANK_ACCOUNT (BANKNUMBER,BANK,ID,PASSWORD,BALANCE,RATE,STATUS,NAME,CREATIONDATE) values ('12340000008','개혁은행','test1234','1234',0,1,'개혁예적금','대기','22/11/19');
Insert into HYEONJU.BANK_ACCOUNT (BANKNUMBER,BANK,ID,PASSWORD,BALANCE,RATE,STATUS,NAME,CREATIONDATE) values ('12340000009','개혁은행','test1234','1234',0,1,'개혁예적금','대기','22/11/19');
Insert into HYEONJU.BANK_ACCOUNT (BANKNUMBER,BANK,ID,PASSWORD,BALANCE,RATE,STATUS,NAME,CREATIONDATE) values ('12340000010','개혁은행',null,'1234',0,1,'개혁예적금','대기','22/11/19');
Insert into HYEONJU.BANK_ACCOUNT (BANKNUMBER,BANK,ID,PASSWORD,BALANCE,RATE,STATUS,NAME,CREATIONDATE) values ('12340000011','개혁은행',null,'1234',0,1,'개혁예적금','대기','22/11/19');
Insert into HYEONJU.BANK_ACCOUNT (BANKNUMBER,BANK,ID,PASSWORD,BALANCE,RATE,STATUS,NAME,CREATIONDATE) values ('12340000013','개혁은행',null,'2345',0,1,'개혁예적금','대기','22/11/19');
Insert into HYEONJU.BANK_ACCOUNT (BANKNUMBER,BANK,ID,PASSWORD,BALANCE,RATE,STATUS,NAME,CREATIONDATE) values ('12340000015','개혁은행',null,'1234',0,1,'개혁예적금','대기','22/11/19');
Insert into HYEONJU.BANK_ACCOUNT (BANKNUMBER,BANK,ID,PASSWORD,BALANCE,RATE,STATUS,NAME,CREATIONDATE) values ('12340000016','개혁은행','test1234','1234',0,1,'개혁예적금','대기','22/11/19');
Insert into HYEONJU.BANK_ACCOUNT (BANKNUMBER,BANK,ID,PASSWORD,BALANCE,RATE,STATUS,NAME,CREATIONDATE) values ('12340000017','개혁은행','test1234','1234',0,1,'개혁예적금','대기','22/11/19');
Insert into HYEONJU.BANK_ACCOUNT (BANKNUMBER,BANK,ID,PASSWORD,BALANCE,RATE,STATUS,NAME,CREATIONDATE) values ('12340000018','개혁은행',null,'1234',0,1,'개혁예적금','대기','22/11/19');
Insert into HYEONJU.BANK_ACCOUNT (BANKNUMBER,BANK,ID,PASSWORD,BALANCE,RATE,STATUS,NAME,CREATIONDATE) values ('12340000019','개혁은행',null,'1234',0,1,'개혁예적금','대기','22/11/19');
Insert into HYEONJU.BANK_ACCOUNT (BANKNUMBER,BANK,ID,PASSWORD,BALANCE,RATE,STATUS,NAME,CREATIONDATE) values ('12340000020','개혁은행',null,'1234',0,1,'개혁예적금','대기','22/11/19');
Insert into HYEONJU.BANK_ACCOUNT (BANKNUMBER,BANK,ID,PASSWORD,BALANCE,RATE,STATUS,NAME,CREATIONDATE) values ('12340000021','개혁은행',null,'1234',0,1,'개혁예적금','대기','22/11/19');
Insert into HYEONJU.BANK_ACCOUNT (BANKNUMBER,BANK,ID,PASSWORD,BALANCE,RATE,STATUS,NAME,CREATIONDATE) values ('12340000022','개혁은행',null,'1234',0,1,'개혁예적금','대기','22/11/19');
Insert into HYEONJU.BANK_ACCOUNT (BANKNUMBER,BANK,ID,PASSWORD,BALANCE,RATE,STATUS,NAME,CREATIONDATE) values ('12340000023','개혁은행',null,'1234',0,1,'개혁예적금','대기','22/11/19');
Insert into HYEONJU.BANK_ACCOUNT (BANKNUMBER,BANK,ID,PASSWORD,BALANCE,RATE,STATUS,NAME,CREATIONDATE) values ('12340000024','개혁은행',null,'1234',0,1,'개혁예적금','대기','22/11/19');
Insert into HYEONJU.BANK_ACCOUNT (BANKNUMBER,BANK,ID,PASSWORD,BALANCE,RATE,STATUS,NAME,CREATIONDATE) values ('12340000025','개혁은행','test1234','qwe123',0,1,'개혁예적금','대기','22/11/19');
Insert into HYEONJU.BANK_ACCOUNT (BANKNUMBER,BANK,ID,PASSWORD,BALANCE,RATE,STATUS,NAME,CREATIONDATE) values ('12340000026','개혁은행','test1234','qwe123',0,1,'개혁예적금','대기','22/11/19');
Insert into HYEONJU.BANK_ACCOUNT (BANKNUMBER,BANK,ID,PASSWORD,BALANCE,RATE,STATUS,NAME,CREATIONDATE) values ('12340000027','개혁은행','test1234','1234',0,1,'개혁예적금','대기','22/11/19');
Insert into HYEONJU.BANK_ACCOUNT (BANKNUMBER,BANK,ID,PASSWORD,BALANCE,RATE,STATUS,NAME,CREATIONDATE) values ('12340000028','개혁은행','test1234','qwe123',0,1,'개혁예적금','대기','22/11/19');
Insert into HYEONJU.BANK_ACCOUNT (BANKNUMBER,BANK,ID,PASSWORD,BALANCE,RATE,STATUS,NAME,CREATIONDATE) values ('12340000029','개혁은행','test1234','qwe123',0,1,'개혁예적금','대기','22/11/19');
Insert into HYEONJU.BANK_ACCOUNT (BANKNUMBER,BANK,ID,PASSWORD,BALANCE,RATE,STATUS,NAME,CREATIONDATE) values ('12340000030','개혁은행','test1234','qwe123',0,1,'개혁예적금','대기','22/11/19');
Insert into HYEONJU.BANK_ACCOUNT (BANKNUMBER,BANK,ID,PASSWORD,BALANCE,RATE,STATUS,NAME,CREATIONDATE) values ('12340000031','개혁은행','test1234','qwe123',0,1,'개혁예적금','대기','22/11/19');
Insert into HYEONJU.BANK_ACCOUNT (BANKNUMBER,BANK,ID,PASSWORD,BALANCE,RATE,STATUS,NAME,CREATIONDATE) values ('12340000032','개혁은행','test1234','qwe123',0,1,'개혁예적금','대기','22/11/19');
Insert into HYEONJU.BANK_ACCOUNT (BANKNUMBER,BANK,ID,PASSWORD,BALANCE,RATE,STATUS,NAME,CREATIONDATE) values ('12340000033','개혁은행','test1234','qwe123',0,1,'개혁예적금','대기','22/11/19');
REM INSERTING into HYEONJU.DEAL
SET DEFINE OFF;
REM INSERTING into HYEONJU.MEMBER
SET DEFINE OFF;
Insert into HYEONJU.MEMBER (ID,NAME,PASSWORD,BIRTH,EMAIL,TEL,GENDER,RANK) values ('test1234','조현주','qwe123','000530','hyeonju.dlf@gmai','male','01012341234',1);
Insert into HYEONJU.MEMBER (ID,NAME,PASSWORD,BIRTH,EMAIL,TEL,GENDER,RANK) values ('test123445','조현주','qwe123','000530','hyeonju.dlf@gmai','male','01012341234',1);
REM INSERTING into HYEONJU.POST
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index ADMIN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HYEONJU"."ADMIN_PK" ON "HYEONJU"."ADMIN" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index POST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HYEONJU"."POST_PK" ON "HYEONJU"."POST" ("no") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MEMBER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HYEONJU"."MEMBER_PK" ON "HYEONJU"."MEMBER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BANK_NAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "HYEONJU"."BANK_NAME" ON "HYEONJU"."BANK" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BANK_ACCOUNT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HYEONJU"."BANK_ACCOUNT_PK" ON "HYEONJU"."BANK_ACCOUNT" ("BANKNUMBER", "BANK") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HYEONJU"."TABLE1_PK" ON "HYEONJU"."DEAL" ("no") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table DEAL
--------------------------------------------------------

  ALTER TABLE "HYEONJU"."DEAL" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("no")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HYEONJU"."DEAL" MODIFY ("no" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table POST
--------------------------------------------------------

  ALTER TABLE "HYEONJU"."POST" ADD CONSTRAINT "POST_PK" PRIMARY KEY ("no")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HYEONJU"."POST" MODIFY ("no" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BANK
--------------------------------------------------------

  ALTER TABLE "HYEONJU"."BANK" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "HYEONJU"."BANK" ADD CONSTRAINT "BANK_NAME" PRIMARY KEY ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HYEONJU"."BANK" MODIFY ("rate" NOT NULL ENABLE);
  ALTER TABLE "HYEONJU"."BANK" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "HYEONJU"."MEMBER" ADD CONSTRAINT "MEMBER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HYEONJU"."MEMBER" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ADMIN
--------------------------------------------------------

  ALTER TABLE "HYEONJU"."ADMIN" ADD CONSTRAINT "ADMIN_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HYEONJU"."ADMIN" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BANK_ACCOUNT
--------------------------------------------------------

  ALTER TABLE "HYEONJU"."BANK_ACCOUNT" ADD CONSTRAINT "BANK_ACCOUNT_PK" PRIMARY KEY ("BANKNUMBER", "BANK")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HYEONJU"."BANK_ACCOUNT" MODIFY ("BANK" NOT NULL ENABLE);
  ALTER TABLE "HYEONJU"."BANK_ACCOUNT" MODIFY ("BANKNUMBER" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BANK_ACCOUNT
--------------------------------------------------------

  ALTER TABLE "HYEONJU"."BANK_ACCOUNT" ADD CONSTRAINT "BANK" FOREIGN KEY ("BANK")
	  REFERENCES "HYEONJU"."BANK" ("NAME") ENABLE;
  ALTER TABLE "HYEONJU"."BANK_ACCOUNT" ADD CONSTRAINT "USERID" FOREIGN KEY ("ID")
	  REFERENCES "HYEONJU"."MEMBER" ("ID") ENABLE;
